Error handling refactor
AFKabl3/AIChess pull request #47
Opened 2024-12-22 14:01 UTC by Gjovani872

Refactored some of the error handling functionalities in the backend routes.py file.
Created a class where there a defined functions that return errors, based on the context of the current program point.

2024-12-22 15:22 UTC, Gjovani872 commented
This PR, if merged, should be the last PR merged, because here I changed some lines in the request-response,http test file.

2024-12-23 13:30 UTC, BONSURHA reviewed
you can add in each function in `routes.py`, after you check that is not `stockfish.is_fen_valid(fen)`, another condition called `stockfish.is_game_over(fen)`  and if is true return something to the frontend else return as before incorrect fen. This is the function, add it in `StockfishEngine.py`:
`    def is_game_over(self, fen):
        board = Board(fen)
        return board.is_checkmate() or board.is_stalemate() or board.is_insufficient_material()`

2024-12-23 13:32 UTC, BONSURHA approved these changes

2024-12-23 13:32 UTC, BONSURHA commented on backend/app/error_handlers.py
you have to put this file in a package, so it respected the rules in the backend structure

2024-12-23 16:32 UTC, BONSURHA commented
python chess library that we are using now: [python-chess](https://python-chess.readthedocs.io/en/latest/).
A reminder of what I said to you in the meeting:
`stockfish.is_fen_valid(fen)` check only if the fen has all the fields (6) and the fen provided is related to a checkmate, so in the backend we can do it -> check if the fields are 6 -> if are 6 we can apply some simple check on the fen using the `Board` class in `chess` library (firstly see in is valid using `Board.is_valid()` and if its valid check if the user provide an instance of a game that is done, using `Board.is_checkmate()` ecc..)

2024-12-30 22:00 UTC, BONSURHA requested changes
re-ask me the review after you finish the update

2025-01-05 21:33 UTC, BONSURHA approved these changes
lgtm

2025-01-05 21:34 UTC, merged